apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fin-advisor
  name: fin-advisor
  namespace: fin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fin-advisor
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fin-advisor
    spec:
      containers:
      - image: fmaced1/fin-advisor:1.0.5
        name: fin-advisor
        ports:
          - name: dash
            containerPort: 8501
        resources: {}
        env:
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: "6379"
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /app
            name: app
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: app
          hostPath:
            path: /app
status: {}
