apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fin-advisor
  name: fin-advisor
  namespace: fin
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: fin-advisor
  type: NodePort
status:
  loadBalancer: {}
