version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  fin-advisor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fin-advisor
    networks:
      - app-network
    ports:
      - "8501:8501"
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge