apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJmbWFjZWQxIiwicGFzc3dvcmQiOiJENHJrbiFnaHQiLCJlbWFpbCI6ImZhYnJpY2lvLm9zYXNtYWRAZ21haWwuY29tIiwiYXV0aCI6IlptMWhZMlZrTVRwRU5ISnJiaUZuYUhRPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
